<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Description" data-toc-modified-id="Description-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Description</a></span></li><li><span><a href="#Import" data-toc-modified-id="Import-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import</a></span></li><li><span><a href="#Array-creation" data-toc-modified-id="Array-creation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Array creation</a></span></li><li><span><a href="#Prime-Numbers" data-toc-modified-id="Prime-Numbers-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Prime Numbers</a></span></li><li><span><a href="#Element-wise-Multiplication" data-toc-modified-id="Element-wise-Multiplication-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Element-wise Multiplication</a></span></li><li><span><a href="#Replacement" data-toc-modified-id="Replacement-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Replacement</a></span></li><li><span><a href="#Axis-Swap" data-toc-modified-id="Axis-Swap-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Axis Swap</a></span></li><li><span><a href="#Transposing" data-toc-modified-id="Transposing-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Transposing</a></span></li><li><span><a href="#Matrix-Multiplication" data-toc-modified-id="Matrix-Multiplication-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Matrix Multiplication</a></span></li><li><span><a href="#Cartesian-Prodoct" data-toc-modified-id="Cartesian-Prodoct-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Cartesian Prodoct</a></span></li><li><span><a href="#Sum-along-Axis" data-toc-modified-id="Sum-along-Axis-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Sum along Axis</a></span></li><li><span><a href="#Determinant" data-toc-modified-id="Determinant-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Determinant</a></span></li></ul></div>

## Description
Numpy is one of the most important Python libraries in data science. In this problem, we are going to get familiar with this library. 

**Note**: In the following cells, the input of each cell is the output of its previous cell. So, order of execution of the cells is important.

## Import 
Put all of your imports for this file in the below cell.

In [2]:
import numpy as np

## Array creation
Create the followings to numpy array:
* A: a 3\*3 array that filled with number 1 to 9 row wise. like this:
$$
A = \left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$ 
* B: a 3\*3\*5 that filled with the numbers start from 11 and have steps of 3 to the end. The array should be filled first along the first dimension then the second dimension and at last the third dimension. like this:
$$
B[:, :, 0] = \left(\begin{array}{cc} 
11 & 20 & 29\\
14 & 23 & 32\\
17 & 26 & 35
\end{array}\right)
$$ 

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array(range(11, 146, 3))
B = x.reshape(5, 3, 3)
B = B.transpose(2, 1, 0)
print('A:\n', A)
print('\nB[:,:,0]\n', B[:,:,0])
#uncomment the following line to print all elements of B:
# print('\n', B)

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B[:,:,0]
 [[11 20 29]
 [14 23 32]
 [17 26 35]]


## Prime Numbers 
Replace the elements with prime values in the array A with 10.

In [4]:
#defining a function that determines if its inpute is a prime number or not:
def isprime(n):
    if n < 2:
        return False
    elif n == 2:
        return True
    else:
        for i in range(2, n):
                if n % i == 0:
                    return False
        return True
#vectorizing isprime:       
v = np.vectorize(isprime)
# applying v to A and replacing prime numbers with 10:
A[v(A)] = 10
print('A:\n', A)

A:
 [[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]


## Element-wise Multiplication
Calculate the element wise multiplication of arrays A and B and put the result in B. Then print the result.

In [5]:
#With a for loop:
'''
result = np.zeros((3, 3, 5))
for i in range(5):
    B[:, :, i] = A * B[:, :, i]
'''
#Without a for loop:
B = (B.transpose() * A.transpose()).transpose()

print('B[:,:,0]:\n',B[:,:,0],'\n')
print('B[:,:,1]:\n',B[:,:,1],'\n')
print('B[:,:,2]:\n',B[:,:,2],'\n')
print('B[:,:,3]:\n',B[:,:,3],'\n')
print('B[:,:,4]:\n',B[:,:,4])
#uncomment the following line to print all elements of B:
# print('\n', B)

B[:,:,0]:
 [[ 11 200 290]
 [ 56 230 192]
 [170 208 315]] 

B[:,:,1]:
 [[ 38 470 560]
 [164 500 354]
 [440 424 558]] 

B[:,:,2]:
 [[ 65 740 830]
 [272 770 516]
 [710 640 801]] 

B[:,:,3]:
 [[  92 1010 1100]
 [ 380 1040  678]
 [ 980  856 1044]] 

B[:,:,4]:
 [[ 119 1280 1370]
 [ 488 1310  840]
 [1250 1072 1287]]


## Replacement
Replace the last slice of array B (B[:, :, 4]) with values of A. Then print the result.

In [6]:
B[:, :, 4] = A
print('B[:,:,4]:\n',B[:,:, 4])
#uncomment the following line to print all elements of B:
# print('\n', B)

B[:,:,4]:
 [[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]


## Axis Swap 
Swap the first(B[:, :, 0]) and last(B[:, :, 4]) slice of the array B **only with one line of code**. Then print the result.

In [7]:
# notice: by numpy assigns matices by reference and we have to use copy() function to avoid it.
B[:, :, 0], B[:, :, 4] = B[:, :, 4].copy(), B[:, :, 0].copy()

print('B[:, :, 0]:\n', B[:, :, 0])
print('\nB[:, :, 4]\n', B[:, :, 4])
#uncomment the following line to print all elements of B:
# print('\n', B)

B[:, :, 0]:
 [[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]

B[:, :, 4]
 [[ 11 200 290]
 [ 56 230 192]
 [170 208 315]]


## Transposing 
Transpose the array B elements in each slice. Then print the result.

In [8]:
B = B.transpose(1, 0, 2)

print('B[:,:,0]:\n',B[:,:,0],'\n')
print('B[:,:,1]:\n',B[:,:,1],'\n')
print('B[:,:,2]:\n',B[:,:,2],'\n')
print('B[:,:,3]:\n',B[:,:,3],'\n')
print('B[:,:,4]:\n',B[:,:,4])
print(B)

B[:,:,0]:
 [[ 1  4 10]
 [10 10  8]
 [10  6  9]] 

B[:,:,1]:
 [[ 38 164 440]
 [470 500 424]
 [560 354 558]] 

B[:,:,2]:
 [[ 65 272 710]
 [740 770 640]
 [830 516 801]] 

B[:,:,3]:
 [[  92  380  980]
 [1010 1040  856]
 [1100  678 1044]] 

B[:,:,4]:
 [[ 11  56 170]
 [200 230 208]
 [290 192 315]]
[[[   1   38   65   92   11]
  [   4  164  272  380   56]
  [  10  440  710  980  170]]

 [[  10  470  740 1010  200]
  [  10  500  770 1040  230]
  [   8  424  640  856  208]]

 [[  10  560  830 1100  290]
  [   6  354  516  678  192]
  [   9  558  801 1044  315]]]


## Matrix Multiplication
Calculate the matrix multiplication of all slices of the array B. 
(B[:, :, 0] \* B[:, :, 1] \* B[:, :, 2] \* B[:, :, 3] \* B[:, :, 4]). Then print the result.

**Note**: the result should be a 3\*3 array. 

In [29]:
# result = np.matmul(B[:, :, 0], B[:, :, 1])
# result = np.matmul(result, B[:, :, 2])
# result = np.matmul(result, B[:, :, 3])
# result = np.matmul(result, B[:, :, 4])
result = B[:, :, 0] @ B[:, :, 1] @ B[:, :, 2] @ B[:, :, 3] @ B[:, :, 4]
print('result:\n', result)

result:
 [[ 1209391816 -1143185392   350988760]
 [ 1470082208  -459189056   415182432]
 [  -38600768  1525962136   425960024]]


## Cartesian Prodoct
Calculate the cartesian product of all columns of the array and put them in one slice. Then print the result.

**Note**: the result should be a 3\*3\*3\*3 array. 

In [30]:
r = np.array(np.meshgrid(result[:, 0], result[:, 1], result[:, 2]))
print(r)

[[[[ 1209391816  1209391816  1209391816]
   [ 1470082208  1470082208  1470082208]
   [  -38600768   -38600768   -38600768]]

  [[ 1209391816  1209391816  1209391816]
   [ 1470082208  1470082208  1470082208]
   [  -38600768   -38600768   -38600768]]

  [[ 1209391816  1209391816  1209391816]
   [ 1470082208  1470082208  1470082208]
   [  -38600768   -38600768   -38600768]]]


 [[[-1143185392 -1143185392 -1143185392]
   [-1143185392 -1143185392 -1143185392]
   [-1143185392 -1143185392 -1143185392]]

  [[ -459189056  -459189056  -459189056]
   [ -459189056  -459189056  -459189056]
   [ -459189056  -459189056  -459189056]]

  [[ 1525962136  1525962136  1525962136]
   [ 1525962136  1525962136  1525962136]
   [ 1525962136  1525962136  1525962136]]]


 [[[  350988760   415182432   425960024]
   [  350988760   415182432   425960024]
   [  350988760   415182432   425960024]]

  [[  350988760   415182432   425960024]
   [  350988760   415182432   425960024]
   [  350988760   415182432   425960024

## Sum along Axis
Calculate the sum of values of the array along its two last dimensions. Then print it. 

**Note**: the result is a 3\*3 array. 

In [31]:
m = np.sum(r, axis=(2,3))
print(m)

[[ -667314824  -667314824  -667314824]
 [-1698733936   162265792   848757336]
 [ -718573648  -718573648  -718573648]]


## Determinant
Calculate the determinant of the array and print it.

In [42]:
# Theoretically .transpose() doesn't do anything but if I don't use it the answer won't be correct!!!
print(np.linalg.det(m.transpose()))

0.0
